[book]
authors = ["Federico Ponzi"]
language = "en"
multilingual = false
src = "src"
title = "TLA+ Wiki"

[preprocessor.katex]
after = ["links"]
block-delimiter = { left = "\\[", right = "\\]" }

[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/FedericoPonzi/tlaplus-wiki"
additional-css = ["last-changed.css"]
# The basic mathjax-support is weird and limited.
mathjax-support = false
