[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]
[book]
authors = ["Federico Ponzi"]
language = "en"
multilingual = false
src = "src"
title = "TLA+ Wiki"

[output.html]
# Optional: Your repository URL used in the link.
git-repository-url = "https://github.com/FedericoPonzi/tlaplus-wiki"
additional-css = ["last-changed.css"]